const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Tween,
		C3.Behaviors.DragnDrop,
		C3.Plugins.NinePatch,
		C3.Behaviors.Fade,
		C3.Behaviors.MoveTo,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Tilemap,
		C3.Plugins.Avix_PokiSDK_ForC3,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.AJAX,
		C3.Plugins.Browser,
		C3.Plugins.Json,
		C3.Plugins.Arr,
		C3.Plugins.Dictionary,
		C3.Behaviors.EightDir,
		C3.Behaviors.solid,
		C3.Behaviors.Pathfinding,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.PokiSDKLoaded,
		C3.ScriptsInEvents.Sdk_Event7,
		C3.ScriptsInEvents.Sdk_Event13,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.CommercialBreakPossible,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.RequestCommercialBreak,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.AdBlockDetected,
		C3.ScriptsInEvents.Sdk_Event23,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.RequestRewardedBreak,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.NotifyLoadingFinished,
		C3.ScriptsInEvents.Sdk_Event31,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.HappyTime,
		C3.ScriptsInEvents.Sdk_Event37,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.NotifyGameplayStart,
		C3.ScriptsInEvents.Sdk_Event43,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.NotifyGameplayStop,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.OnCommercialBreakComplete,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.OnRewardedBreakComplete,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.LastAdRewardSuccess,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.NinePatch.Cnds.PickChildren,
		C3.Plugins.System.Exps.projectversion,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Dictionary.Exps.GetDefault,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.System.Acts.SortZOrderByInstVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Browser.Exps.Language,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.Arr.Acts.Push,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{ScrollTo: 0},
	{camera: 0},
	{cursor: 0},
	{is_pressed: 0},
	{ui_action_button: 0},
	{ui_block_clicking: 0},
	{id: 0},
	{subid: 0},
	{state: 0},
	{is_blocked: 0},
	{index: 0},
	{value_int_1: 0},
	{value_int_2: 0},
	{Tween: 0},
	{ui_button_18x18: 0},
	{ui_button_28x28: 0},
	{ui_button_66x14: 0},
	{ui_button_66x28: 0},
	{ui_button_96x28: 0},
	{ui_button_dark_28x28: 0},
	{group_id: 0},
	{value: 0},
	{value_str: 0},
	{ui_checkbox: 0},
	{ui_joystick: 0},
	{ui_joystick_bg: 0},
	{x_min: 0},
	{x_max: 0},
	{DragDrop: 0},
	{ui_slider: 0},
	{ui_slider_background: 0},
	{ui_window: 0},
	{ui_window_head: 0},
	{ui_window_panel: 0},
	{ui_control_detect: 0},
	{ui_button_28x28_close: 0},
	{ui_button_28x28_accept: 0},
	{ui_dark_background: 0},
	{ui_button_28x28_settings: 0},
	{main_values: 0},
	{Fade: 0},
	{MoveTo: 0},
	{gold_notify: 0},
	{zone_type: 0},
	{zone_subtype: 0},
	{reward_type: 0},
	{ad_gold_button: 0},
	{ui_exp_bar: 0},
	{ui_window_blue: 0},
	{ui_chest: 0},
	{ui_icon_48x48: 0},
	{label: 0},
	{add_point: 0},
	{fighter_value: 0},
	{fighter_values: 0},
	{add_big_point: 0},
	{ui_circle_progress: 0},
	{circle_progress_value: 0},
	{circle_progress_level: 0},
	{circle_progress_bg: 0},
	{ui_logo: 0},
	{ui_loading_progress_bar: 0},
	{ui_touch_notify: 0},
	{ad_gold_button_bg: 0},
	{character_shadow: 0},
	{bar: 0},
	{destroy_effect: 0},
	{order: 0},
	{type: 0},
	{subtype: 0},
	{strength: 0},
	{agility: 0},
	{stamina: 0},
	{money: 0},
	{hp: 0},
	{is_dead: 0},
	{dead_timer: 0},
	{trophy: 0},
	{fighter_1: 0},
	{prev_x: 0},
	{prev_y: 0},
	{direction: 0},
	{zone_animation: 0},
	{zone_linked_object_uid: 0},
	{zone_delay: 0},
	{zone_timer: 0},
	{next_zone_uid: 0},
	{fact_zone_uid: 0},
	{location: 0},
	{npc_1: 0},
	{npc_2: 0},
	{npc_3: 0},
	{npc_4: 0},
	{npc_5: 0},
	{policeman_1: 0},
	{policeman_2: 0},
	{policeman_3: 0},
	{policeman_4: 0},
	{chief_1: 0},
	{doctor_1: 0},
	{fighter_2: 0},
	{fighter_3: 0},
	{fighter_4: 0},
	{fighter_5: 0},
	{fighter_6: 0},
	{fighter_7: 0},
	{fighter_8: 0},
	{fighter_9: 0},
	{fighter_10: 0},
	{npc_6: 0},
	{npc_7: 0},
	{npc_8: 0},
	{is_now_sound: 0},
	{zone_value: 0},
	{zone_x: 0},
	{zone_y: 0},
	{got_hit: 0},
	{prev_frame: 0},
	{hero_1: 0},
	{hero_2: 0},
	{skin: 0},
	{hero_3: 0},
	{hero_4: 0},
	{hero_5: 0},
	{hero_6: 0},
	{hero_7: 0},
	{hero_8: 0},
	{hero_9: 0},
	{hero_10: 0},
	{npc_9: 0},
	{npc_10: 0},
	{fighter_11: 0},
	{fighter_12: 0},
	{fighter_13: 0},
	{fighter_14: 0},
	{fighter_15: 0},
	{hero_11: 0},
	{hero_12: 0},
	{hero_13: 0},
	{hero_14: 0},
	{hero_15: 0},
	{hero_16: 0},
	{hero_17: 0},
	{prison_bar: 0},
	{is_closed: 0},
	{prison_bar_door: 0},
	{bed: 0},
	{toilet: 0},
	{toilet_paper: 0},
	{prison_window: 0},
	{table: 0},
	{prison_camera: 0},
	{table2: 0},
	{photos: 0},
	{wall: 0},
	{cafe_table: 0},
	{cooking_table: 0},
	{cafe_closet_1: 0},
	{cafe_closet_2: 0},
	{food: 0},
	{prison_bar_door2: 0},
	{punching_bug: 0},
	{sport_carpet: 0},
	{treadmill: 0},
	{weight: 0},
	{tape_recorder: 0},
	{mirror: 0},
	{shower_wall: 0},
	{shower_hole: 0},
	{shower_items: 0},
	{shower: 0},
	{control_screens: 0},
	{control_table: 0},
	{control_chair: 0},
	{control_server: 0},
	{delay: 0},
	{timer: 0},
	{value1int: 0},
	{animation: 0},
	{zone_default: 0},
	{hospital_bed: 0},
	{iv_drip: 0},
	{hospital_monitor: 0},
	{hospital_table: 0},
	{hospital_chair: 0},
	{basketball_hoop: 0},
	{basketball_area: 0},
	{soccer_area: 0},
	{soccer_gate: 0},
	{body_builder: 0},
	{barbell: 0},
	{amplifier: 0},
	{helicopter: 0},
	{helicopter_base: 0},
	{car_police: 0},
	{sign_stop: 0},
	{ui_path_arrow: 0},
	{Sine: 0},
	{finger: 0},
	{ui_button_notify: 0},
	{ui_wasd_notify: 0},
	{ui_path_target: 0},
	{collisions: 0},
	{walls: 0},
	{floors: 0},
	{walls_borders: 0},
	{city_floors: 0},
	{PokiSDK: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{Touch: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{AJAX: 0},
	{Browser: 0},
	{data: 0},
	{data_settings: 0},
	{data_game: 0},
	{exp_values: 0},
	{text: 0},
	{hero_values: 0},
	{upgrades: 0},
	{upgrade_values: 0},
	{owner_uid: 0},
	{linked_object_uid: 0},
	{npc_zone: 0},
	{random_npc_zone_uids: 0},
	{skin_values: 0},
	{Button: 0},
	{UiElement: 0},
	{Icon: 0},
	{ButtonIcon: 0},
	{Ui9PatchElement: 0},
	{"8Direction": 0},
	{Solid: 0},
	{Hero: 0},
	{ZIndex: 0},
	{TilemapSolid: 0},
	{Window: 0},
	{DoorMaster: 0},
	{Door: 0},
	{InteractObject: 0},
	{PunchingBag: 0},
	{Zone: 0},
	{ZoneLinkedObject: 0},
	{Fighter: 0},
	{Fade2: 0},
	{MoveTo2: 0},
	{AddPoint: 0},
	{Pathfinding: 0},
	{Npc: 0},
	{NpcZone: 0},
	{SimpleNpc: 0},
	{LOADED_COUNTER: 0},
	{LOADED_EXPECTED: 0},
	{IS_DEBUG_MODE: 0},
	{IS_NEW_GAME: 0},
	{RESET_TIMER: 0},
	{SAVE_TIMER: 0},
	{DECORATION_COLOR_1: 0},
	{DECORATION_COLOR_2: 0},
	{DECORATION_COLOR_3: 0},
	{DECORATION_COLOR_4: 0},
	{SDK_TYPE__CRAZY_GAMES: 0},
	{SDK_TYPE__POKI: 0},
	{SDK_TYPE: 0},
	{IS_SDK_LOADED: 0},
	{REWARD_TYPE: 0},
	{REWARD_VALUE_1: 0},
	{REWARD_VALUE_2: 0},
	{REWARD_VALUE_3: 0},
	{MIDROLL_TYPE: 0},
	{MIDROLL_TYPE__AFTER_PAUSE: 0},
	{MIDROLL_TYPE__AFTER_DEAD: 0},
	{MIDROLL_TYPE__AFTER_UPGRADE: 0},
	{MIDROLL_TYPE__AFTER_SHOWER: 0},
	{REWARD_TRAIN_BONUS: 0},
	{REWARD_FREE_GOLD: 0},
	{PERIOD_BETWEEN_AD: 0},
	{value1: 0},
	{value2: 0},
	{value3: 0},
	{CURRENT_HERO_SKIN_INDEX: 0},
	{CHARACTER_ANIM_IDLE: 0},
	{CHARACTER_ANIM_WALK: 0},
	{CHARACTER_ANIM__RIGHT: 0},
	{CHARACTER_ANIM__LEFT: 0},
	{CHARACTER_ANIM__UP: 0},
	{CHARACTER_ANIM__DOWN: 0},
	{CHARACTER_ANIM__CARRY: 0},
	{CHARACTER_ANIM__OFF: 0},
	{HERO_VALUE__MONEY: 0},
	{HERO_VALUE__STRENGTH: 0},
	{HERO_VALUE__AGILITY: 0},
	{HERO_VALUE__STAMINA: 0},
	{FIGHT_TIMER: 0},
	{FIGHT_TICK_DELAY: 0},
	{CURRENT_TRAIN_BONUS: 0},
	{CURRENT_TRAIN_BONUS_TIMER: 0},
	{CURRENT_TRAIN_BONUS_DELAY: 0},
	{is_moving: 0},
	{start_animation: 0},
	{next_animation: 0},
	{prev_state: 0},
	{fight_tick_result: 0},
	{result: 0},
	{points: 0},
	{fighter_uid: 0},
	{x: 0},
	{y: 0},
	{skin_index: 0},
	{LAYER_MOBILE: 0},
	{IS_MOBILE: 0},
	{IS_MOBILE_DETECTED: 0},
	{joystick_angle: 0},
	{joystick_distance: 0},
	{MUSIC_VOLUME_RANGE: 0},
	{SOUND_VOLUME_RANGE: 0},
	{CURRENT_MUSIC_VOLUME_PERCENT: 0},
	{CURRENT_SOUND_VOLUME_PERCENT: 0},
	{CURRENT_SOUND_VOLUME: 0},
	{CURRENT_MUSIC_VOLUME: 0},
	{SND_LOSE: 0},
	{SND_TREADMILL_LOOP: 0},
	{SND_METAL_1: 0},
	{SND_METAL_2: 0},
	{SND_UPGRADE: 0},
	{SND_COINS: 0},
	{SND_EATING: 0},
	{SND_ERROR: 0},
	{SND_PUNCH_1: 0},
	{SND_PUNCH_2: 0},
	{SND_LEVEL_UP: 0},
	{SND_DOOR: 0},
	{SND_SHOWER_LOOP: 0},
	{MUSIC_STATE: 0},
	{SOUND_STATE: 0},
	{random_index: 0},
	{sound_type: 0},
	{volume_delta: 0},
	{LAYER_POINTS: 0},
	{subId: 0},
	{uid: 0},
	{start_x: 0},
	{start_y: 0},
	{is_big: 0},
	{LAYER_SETTINGS: 0},
	{IS_SETTINGS_SHOW: 0},
	{IS_SETTINGS_READY: 0},
	{without_pause: 0},
	{event_id: 0},
	{SCREEN_WIDTH: 0},
	{SCREEN_HEIGHT: 0},
	{LAYER_TOP_PANEL: 0},
	{LAYER_UI_MAIN_VALUES: 0},
	{AD_FREE_GOLD_TIMER: 0},
	{upgrade_index: 0},
	{delta: 0},
	{IS_PATH: 0},
	{IS_FINGER: 0},
	{PATH_TO_X: 0},
	{PATH_TO_Y: 0},
	{IS_WASD: 0},
	{NOTIFY_START_X: 0},
	{NOTIFY_START_Y: 0},
	{CURRENT_TUTORIAL_STEP: 0},
	{PREV_TUTORIAL_STEP: 0},
	{PATH_MIN_DIST: 0},
	{TUTORIAL_SIZE: 0},
	{distance_to: 0},
	{distance_to2: 0},
	{to_x: 0},
	{to_y: 0},
	{IS_PAUSED: 0},
	{IS_FIRST_PLAYER_ITERACTION: 0},
	{LAYER_WORLD: 0},
	{LAYER_WORLD_UI: 0},
	{CURRENT_LOCATION: 0},
	{LOCATION_CAVE: 0},
	{LOCATION_HOUSE: 0},
	{INTERACT_OBJ__DISTANCE: 0},
	{dist_to_obj: 0},
	{ZONE_TYPE__BOXING_BAG: 0},
	{ZONE_TYPE__TREADMILLS: 0},
	{ZONE_TYPE__WEIGHTS: 0},
	{ZONE_TYPE__FIGHTER: 0},
	{ZONE_TYPE__UPGRADE_1: 0},
	{ZONE_TYPE__UPGRADE_2: 0},
	{ZONE_TYPE__UPGRADE_3: 0},
	{ZONE_TYPE__FOOD: 0},
	{ZONE_TYPE__SHOWER: 0},
	{ZONE_TYPE__SKIN: 0},
	{CURRENT_LANG: 0},
	{UPGRADE_START_PRICE: 0},
	{tick_value: 0},
	{price: 0},
	{current_value: 0},
	{upgrade_value: 0},
	{next_npc_zone_uid: 0},
	{dlt_x: 0},
	{dlt_y: 0},
	{zone_uid: 0},
	{npc_zone_uid: 0},
	{npc_uid: 0},
	{current_zone_type: 0},
	{GLOBAL_TIMER: 0},
	{RESET_COUNTER: 0},
	{SKIN_START_PRICE: 0}
];

self.InstanceType = {
	camera: class extends self.ISpriteInstance {},
	cursor: class extends self.ISpriteInstance {},
	ui_action_button: class extends self.ISpriteInstance {},
	ui_block_clicking: class extends self.ISpriteInstance {},
	ui_button_18x18: class extends self.ISpriteInstance {},
	ui_button_28x28: class extends self.ISpriteInstance {},
	ui_button_66x14: class extends self.ISpriteInstance {},
	ui_button_66x28: class extends self.ISpriteInstance {},
	ui_button_96x28: class extends self.ISpriteInstance {},
	ui_button_dark_28x28: class extends self.ISpriteInstance {},
	ui_checkbox: class extends self.ISpriteInstance {},
	ui_joystick: class extends self.ISpriteInstance {},
	ui_joystick_bg: class extends self.ISpriteInstance {},
	ui_slider: class extends self.ISpriteInstance {},
	ui_slider_background: class extends self.ISpriteInstance {},
	ui_window: class extends self.IWorldInstance {},
	ui_window_head: class extends self.IWorldInstance {},
	ui_window_panel: class extends self.IWorldInstance {},
	ui_control_detect: class extends self.ISpriteInstance {},
	ui_button_28x28_close: class extends self.ISpriteInstance {},
	ui_button_28x28_accept: class extends self.ISpriteInstance {},
	ui_dark_background: class extends self.ISpriteInstance {},
	ui_button_28x28_settings: class extends self.ISpriteInstance {},
	main_values: class extends self.ISpriteInstance {},
	gold_notify: class extends self.ISpriteInstance {},
	ad_gold_button: class extends self.ISpriteInstance {},
	ui_exp_bar: class extends self.ISpriteInstance {},
	ui_window_blue: class extends self.IWorldInstance {},
	ui_chest: class extends self.ISpriteInstance {},
	ui_icon_48x48: class extends self.ISpriteInstance {},
	label: class extends self.ITextInstance {},
	add_point: class extends self.ITextInstance {},
	fighter_value: class extends self.ITextInstance {},
	fighter_values: class extends self.ISpriteInstance {},
	add_big_point: class extends self.ITextInstance {},
	ui_circle_progress: class extends self.ISpriteInstance {},
	circle_progress_value: class extends self.ITextInstance {},
	circle_progress_level: class extends self.ITextInstance {},
	circle_progress_bg: class extends self.ISpriteInstance {},
	ui_logo: class extends self.ISpriteInstance {},
	ui_loading_progress_bar: class extends self.ISpriteInstance {},
	ui_touch_notify: class extends self.ISpriteInstance {},
	ad_gold_button_bg: class extends self.ISpriteInstance {},
	character_shadow: class extends self.ISpriteInstance {},
	bar: class extends self.ISpriteInstance {},
	destroy_effect: class extends self.ISpriteInstance {},
	fighter_1: class extends self.ISpriteInstance {},
	npc_1: class extends self.ISpriteInstance {},
	npc_2: class extends self.ISpriteInstance {},
	npc_3: class extends self.ISpriteInstance {},
	npc_4: class extends self.ISpriteInstance {},
	npc_5: class extends self.ISpriteInstance {},
	policeman_1: class extends self.ISpriteInstance {},
	policeman_2: class extends self.ISpriteInstance {},
	policeman_3: class extends self.ISpriteInstance {},
	policeman_4: class extends self.ISpriteInstance {},
	chief_1: class extends self.ISpriteInstance {},
	doctor_1: class extends self.ISpriteInstance {},
	fighter_2: class extends self.ISpriteInstance {},
	fighter_3: class extends self.ISpriteInstance {},
	fighter_4: class extends self.ISpriteInstance {},
	fighter_5: class extends self.ISpriteInstance {},
	fighter_6: class extends self.ISpriteInstance {},
	fighter_7: class extends self.ISpriteInstance {},
	fighter_8: class extends self.ISpriteInstance {},
	fighter_9: class extends self.ISpriteInstance {},
	fighter_10: class extends self.ISpriteInstance {},
	npc_6: class extends self.ISpriteInstance {},
	npc_7: class extends self.ISpriteInstance {},
	npc_8: class extends self.ISpriteInstance {},
	hero_1: class extends self.ISpriteInstance {},
	hero_2: class extends self.ISpriteInstance {},
	skin: class extends self.ISpriteInstance {},
	hero_3: class extends self.ISpriteInstance {},
	hero_4: class extends self.ISpriteInstance {},
	hero_5: class extends self.ISpriteInstance {},
	hero_6: class extends self.ISpriteInstance {},
	hero_7: class extends self.ISpriteInstance {},
	hero_8: class extends self.ISpriteInstance {},
	hero_9: class extends self.ISpriteInstance {},
	hero_10: class extends self.ISpriteInstance {},
	npc_9: class extends self.ISpriteInstance {},
	npc_10: class extends self.ISpriteInstance {},
	fighter_11: class extends self.ISpriteInstance {},
	fighter_12: class extends self.ISpriteInstance {},
	fighter_13: class extends self.ISpriteInstance {},
	fighter_14: class extends self.ISpriteInstance {},
	fighter_15: class extends self.ISpriteInstance {},
	hero_11: class extends self.ISpriteInstance {},
	hero_12: class extends self.ISpriteInstance {},
	hero_13: class extends self.ISpriteInstance {},
	hero_14: class extends self.ISpriteInstance {},
	hero_15: class extends self.ISpriteInstance {},
	hero_16: class extends self.ISpriteInstance {},
	hero_17: class extends self.ISpriteInstance {},
	prison_bar: class extends self.ISpriteInstance {},
	prison_bar_door: class extends self.ISpriteInstance {},
	bed: class extends self.ISpriteInstance {},
	toilet: class extends self.ISpriteInstance {},
	toilet_paper: class extends self.ISpriteInstance {},
	prison_window: class extends self.ISpriteInstance {},
	table: class extends self.ISpriteInstance {},
	prison_camera: class extends self.ISpriteInstance {},
	table2: class extends self.ISpriteInstance {},
	photos: class extends self.ISpriteInstance {},
	wall: class extends self.ISpriteInstance {},
	cafe_table: class extends self.ISpriteInstance {},
	cooking_table: class extends self.ISpriteInstance {},
	cafe_closet_1: class extends self.ISpriteInstance {},
	cafe_closet_2: class extends self.ISpriteInstance {},
	food: class extends self.ISpriteInstance {},
	prison_bar_door2: class extends self.ISpriteInstance {},
	punching_bug: class extends self.ISpriteInstance {},
	sport_carpet: class extends self.ISpriteInstance {},
	treadmill: class extends self.ISpriteInstance {},
	weight: class extends self.ISpriteInstance {},
	tape_recorder: class extends self.ISpriteInstance {},
	mirror: class extends self.ISpriteInstance {},
	shower_wall: class extends self.ISpriteInstance {},
	shower_hole: class extends self.ISpriteInstance {},
	shower_items: class extends self.ISpriteInstance {},
	shower: class extends self.ISpriteInstance {},
	control_screens: class extends self.ISpriteInstance {},
	control_table: class extends self.ISpriteInstance {},
	control_chair: class extends self.ISpriteInstance {},
	control_server: class extends self.ISpriteInstance {},
	zone_default: class extends self.ISpriteInstance {},
	hospital_bed: class extends self.ISpriteInstance {},
	iv_drip: class extends self.ISpriteInstance {},
	hospital_monitor: class extends self.ISpriteInstance {},
	hospital_table: class extends self.ISpriteInstance {},
	hospital_chair: class extends self.ISpriteInstance {},
	basketball_hoop: class extends self.ISpriteInstance {},
	basketball_area: class extends self.ISpriteInstance {},
	soccer_area: class extends self.ISpriteInstance {},
	soccer_gate: class extends self.ISpriteInstance {},
	body_builder: class extends self.ISpriteInstance {},
	barbell: class extends self.ISpriteInstance {},
	amplifier: class extends self.ISpriteInstance {},
	helicopter: class extends self.ISpriteInstance {},
	helicopter_base: class extends self.ISpriteInstance {},
	car_police: class extends self.ISpriteInstance {},
	sign_stop: class extends self.ISpriteInstance {},
	ui_path_arrow: class extends self.ISpriteInstance {},
	finger: class extends self.ISpriteInstance {},
	ui_button_notify: class extends self.ISpriteInstance {},
	ui_wasd_notify: class extends self.ISpriteInstance {},
	ui_path_target: class extends self.ISpriteInstance {},
	collisions: class extends self.ITilemapInstance {},
	walls: class extends self.ITilemapInstance {},
	floors: class extends self.ITilemapInstance {},
	walls_borders: class extends self.ITilemapInstance {},
	city_floors: class extends self.ITilemapInstance {},
	PokiSDK: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	data: class extends self.IJSONInstance {},
	data_settings: class extends self.IJSONInstance {},
	data_game: class extends self.IJSONInstance {},
	exp_values: class extends self.IArrayInstance {},
	text: class extends self.IJSONInstance {},
	hero_values: class extends self.IDictionaryInstance {},
	upgrades: class extends self.IArrayInstance {},
	upgrade_values: class extends self.IArrayInstance {},
	npc_zone: class extends self.ISpriteInstance {},
	random_npc_zone_uids: class extends self.IArrayInstance {},
	skin_values: class extends self.IArrayInstance {},
	Button: class extends self.ISpriteInstance {},
	UiElement: class extends self.ISpriteInstance {},
	Icon: class extends self.ISpriteInstance {},
	ButtonIcon: class extends self.ISpriteInstance {},
	Ui9PatchElement: class extends self.IWorldInstance {},
	Hero: class extends self.ISpriteInstance {},
	ZIndex: class extends self.ISpriteInstance {},
	TilemapSolid: class extends self.ITilemapInstance {},
	Window: class extends self.IWorldInstance {},
	DoorMaster: class extends self.ISpriteInstance {},
	Door: class extends self.ISpriteInstance {},
	Solid: class extends self.ISpriteInstance {},
	InteractObject: class extends self.ISpriteInstance {},
	PunchingBag: class extends self.ISpriteInstance {},
	Zone: class extends self.ISpriteInstance {},
	ZoneLinkedObject: class extends self.ISpriteInstance {},
	Fighter: class extends self.ISpriteInstance {},
	AddPoint: class extends self.ITextInstance {},
	Npc: class extends self.ISpriteInstance {},
	NpcZone: class extends self.ISpriteInstance {},
	SimpleNpc: class extends self.ISpriteInstance {}
}