const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Avix_PokiSDK_ForC3,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Plugins.AJAX,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Json,
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.Timer,
		C3.Behaviors.Tween,
		C3.Behaviors.bound,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Particles,
		C3.Behaviors.Anchor,
		C3.Behaviors.Sin,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.skymen_tiled_sprite,
		C3.Plugins.NinePatch,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.NotifyGameplayStart,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.NotifyGameplayStop,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.NinePatch.Exps.Count,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.RequestCommercialBreak,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.CommercialBreakPossible,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.OnCommercialBreakComplete,
		C3.Plugins.Avix_PokiSDK_ForC3.Acts.RequestRewardedBreak,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.OnRewardedBreakComplete,
		C3.Plugins.Avix_PokiSDK_ForC3.Cnds.LastAdRewardSuccess,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.Json.Cnds.CompareValue,
		C3.Plugins.Json.Exps.CurrentKey,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Exps.PlaybackTime,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Seek,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Plugins.LocalStorage.Cnds.OnItemSet,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Json.Acts.SetArray,
		C3.Plugins.Json.Acts.SetObject,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Json.Acts.PushValue,
		C3.Plugins.TiledBg.Exps.UID,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.TiledBg.Cnds.PickChildren,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.TiledBg.Cnds.PickByUID,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Exps.BBoxLeft,
		C3.Plugins.TiledBg.Exps.BBoxRight,
		C3.Plugins.TiledBg.Exps.BBoxTop,
		C3.Plugins.TiledBg.Exps.BBoxBottom,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.TiledBg.Exps.BBoxMidX,
		C3.Plugins.TiledBg.Exps.BBoxMidY,
		C3.Plugins.TiledBg.Acts.AddChild,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Behaviors.Sin.Exps.Magnitude,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Behaviors.EightDir.Exps.MaxSpeed,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Behaviors.Sin.Exps.Value,
		C3.Behaviors.EightDir.Exps.VectorX,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.HasChildren,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareChildCount,
		C3.Plugins.Arr.Cnds.OnCreated,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Behaviors.Timer.Exps.Duration,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.TiledBg.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Plugins.Sprite.Exps.BBoxMidX,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.NinePatch.Exps.LayerName,
		C3.Plugins.NinePatch.Exps.BBoxMidX,
		C3.Plugins.NinePatch.Exps.BBoxBottom,
		C3.Plugins.NinePatch.Acts.AddChild,
		C3.Plugins.NinePatch.Exps.BBoxMidY,
		C3.Plugins.System.Exps.min,
		C3.Plugins.NinePatch.Exps.UID,
		C3.Plugins.System.Exps.len,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Cnds.HasParent,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Exps.BBoxMidY,
		C3.Plugins.Particles.Acts.SetXRandomiser,
		C3.Plugins.Particles.Acts.SetYRandomiser,
		C3.Plugins.System.Exps.layertolayerx,
		C3.Plugins.System.Exps.layertolayery,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Plugins.System.Exps.anglelerp,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Behaviors.Sin.Cnds.CompareMagnitude,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.NinePatch.Cnds.PickParent,
		C3.Plugins.NinePatch.Acts.SetY,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.TiledBg.Cnds.IsVisible,
		C3.Plugins.TiledBg.Cnds.OnCreated,
		C3.Plugins.TiledBg.Exps.LayerName,
		C3.Behaviors.Anchor.Acts.SetEnabled,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.TiledBg.Acts.SubInstanceVar,
		C3.Plugins.TiledBg.Exps.Count,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.TiledBg.Exps.IID,
		C3.Plugins.NinePatch.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.NinePatch.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.Sprite.Acts.SetMeshPoint,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Exps.ChildCount,
		C3.Plugins.Sprite.Cnds.PickNthChild,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Behaviors.EightDir.Acts.SetAcceleration,
		C3.Behaviors.Timer.Acts.PauseResumeTimer,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.NinePatch.Cnds.IsOnScreen,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.NinePatch.Acts.SetOpacity,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.find,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Sprite.Acts.SetEffect,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.NinePatch.Cnds.PickChildren,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.MoveToBottom
	];
};
self.C3_JsPropNameTable = [
	{PokiSDK: 0},
	{Keyboard: 0},
	{Touch: 0},
	{PlatformInfo: 0},
	{AJAX: 0},
	{Audio: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{jsonDataMons: 0},
	{jsonSaveField: 0},
	{jsonDataDex: 0},
	{playerFoodStack: 0},
	{playerMonTrail: 0},
	{zort: 0},
	{topException: 0},
	{bottomException: 0},
	{zort_aux: 0},
	{stack: 0},
	{followers: 0},
	{state: 0},
	{baseSpeed: 0},
	{currSpeed: 0},
	{dropRate: 0},
	{step: 0},
	{"8Direction": 0},
	{Timer: 0},
	{Tween: 0},
	{BoundToLayout: 0},
	{player: 0},
	{bgGrass: 0},
	{area: 0},
	{maxOutput: 0},
	{maxMons: 0},
	{currentMons: 0},
	{currentOutput: 0},
	{type: 0},
	{margins: 0},
	{areaActive: 0},
	{txtDisplay: 0},
	{txtData: 0},
	{txtTimer: 0},
	{x0: 0},
	{y0: 0},
	{stackIndex: 0},
	{beingEaten: 0},
	{follow: 0},
	{imgPoint: 0},
	{sprFruit: 0},
	{txtLevel: 0},
	{prtStar: 0},
	{tileArrows: 0},
	{barProgress: 0},
	{Anchor: 0},
	{txtTime: 0},
	{txtScore: 0},
	{price: 0},
	{areaName: 0},
	{areaType: 0},
	{unlockCondition: 0},
	{areaBuy: 0},
	{Sine: 0},
	{sprChar: 0},
	{uiKeyboardInput: 0},
	{DragDrop: 0},
	{sprFruit2: 0},
	{uiMobInputCenter: 0},
	{uiMobInputAxis: 0},
	{sprCoin: 0},
	{uiCoins: 0},
	{txtCash: 0},
	{uiCoinFlying: 0},
	{targetX: 0},
	{targetY: 0},
	{sprBeacon: 0},
	{areaBuildZone: 0},
	{targetUID: 0},
	{uiCoinBuy: 0},
	{secondHalf: 0},
	{radHalfLast: 0},
	{valMax: 0},
	{val: 0},
	{radBase: 0},
	{radMask: 0},
	{radHalfFirst: 0},
	{quadrant: 0},
	{radQuadrant: 0},
	{stage: 0},
	{genes: 0},
	{level: 0},
	{followIndex: 0},
	{hueShift: 0},
	{shiny: 0},
	{currentAreaUID: 0},
	{monBasic: 0},
	{baseScale: 0},
	{facing: 0},
	{lastX: 0},
	{currPos: 0},
	{sprMonInfant: 0},
	{sprMonTeen: 0},
	{sprMonAdult: 0},
	{SineAngle: 0},
	{sprMonEgg: 0},
	{sprShadow: 0},
	{tiled_sprite: 0},
	{sprHintLine: 0},
	{"9pDirt": 0},
	{sprLog: 0},
	{sprRope: 0},
	{sprSign: 0},
	{"9pBubble": 0},
	{sprPoint: 0},
	{sprNeeds: 0},
	{locked: 0},
	{timePanTo: 0},
	{timeStay: 0},
	{timePanBack: 0},
	{zoomValue: 0},
	{zooming: 0},
	{ScrollTo: 0},
	{auxCam: 0},
	{spawnTime: 0},
	{Sine2: 0},
	{sprTree: 0},
	{sprExitPoint: 0},
	{"9pPenFloor": 0},
	{behind: 0},
	{sprKnot: 0},
	{prtShine: 0},
	{sprFruitSpoiled: 0},
	{prtDust: 0},
	{areaTreeBuy: 0},
	{"9pBuySpot": 0},
	{txtDropShadow: 0},
	{sprProps: 0},
	{sprGrass: 0},
	{sprDust: 0},
	{radTimer: 0},
	{prtFlies: 0},
	{uiTutorialMobile: 0},
	{partBasic: 0},
	{minScroll: 0},
	{maxScroll: 0},
	{currentScroll: 0},
	{lastTouch: 0},
	{lastScroll: 0},
	{patMenuBg: 0},
	{Solid: 0},
	{colBasic: 0},
	{boostType: 0},
	{value: 0},
	{areaRewardedAd: 0},
	{uiIconAd: 0},
	{sprBoost: 0},
	{uiBoostIcon: 0},
	{sprAdSpot: 0},
	{sprZoom: 0},
	{sprFarmForeground: 0},
	{SineV: 0},
	{SineH: 0},
	{SineFlutter: 0},
	{SineScale: 0},
	{SineWidth: 0},
	{sprButterfly: 0},
	{prtEvoShine: 0},
	{sprSigns: 0},
	{patMenuFw: 0},
	{action: 0},
	{sprButton: 0},
	{uiDex: 0},
	{prtShineCoin: 0},
	{uiNotification: 0},
	{uiWarning: 0},
	{uiNo: 0},
	{"9pPenDesert": 0},
	{"9pPenWater": 0},
	{"9pPenJungle": 0},
	{"9pPenBreeding": 0},
	{"9pPenEgg": 0},
	{sprCharArm: 0},
	{"9pUiInfo": 0},
	{uiSettings: 0},
	{uiHintColor: 0},
	{uiSFX: 0},
	{uiMusic: 0},
	{patSettingsBg: 0},
	{txtTitle: 0},
	{btnExit: 0},
	{sprDexNotif: 0},
	{sprSparkle: 0},
	{"9pPenAdult": 0},
	{uiPickUp: 0},
	{sprBreedNest: 0},
	{sprFarmLayout3: 0},
	{prtShinySparke: 0},
	{uiShinyDex: 0},
	{famFood: 0},
	{famMons: 0},
	{famSpritesMon: 0},
	{famZorder: 0},
	{famScanAreas: 0},
	{famScanObjects: 0},
	{famAnimDirt: 0},
	{famAnimProp: 0},
	{famDropShadowed: 0},
	{famAreaBuy: 0},
	{famTimeScaledSpr: 0},
	{famDexContent: 0},
	{famZorderParent: 0},
	{Tween2: 0},
	{famSpritesMonAux: 0},
	{famTimeScaledBg: 0},
	{famTimeScaled9p: 0},
	{POKI_firstTap: 0},
	{POKI_gameStart: 0},
	{tag: 0},
	{finalZoom: 0},
	{xStep: 0},
	{xVar: 0},
	{yStep: 0},
	{yVar: 0},
	{ADS_LAST_TAG: 0},
	{ADS_LAST_VALUE: 0},
	{JSONS_PARSED: 0},
	{JSON_FILES_LIST: 0},
	{JSON_PARSING_INDEX: 0},
	{MON_DATA: 0},
	{MON_DEX: 0},
	{monIndex: 0},
	{returnColor: 0},
	{monID: 0},
	{colorIndex: 0},
	{returnIndex: 0},
	{audioFile: 0},
	{pitchRatio: 0},
	{loop: 0},
	{musicFile: 0},
	{MUTE_SFX: 0},
	{MUTE_MUSIC: 0},
	{MUSIC_TRACK: 0},
	{musicHeader: 0},
	{resetMusic: 0},
	{SAVE_DEFAULT_FIELD: 0},
	{SAVE_DEFAULT_DEX: 0},
	{scanIndex: 0},
	{curPathAreas: 0},
	{curPath: 0},
	{curMonUID: 0},
	{auxNestIndex: 0},
	{currGenes: 0},
	{currLevel: 0},
	{currStage: 0},
	{tolerance: 0},
	{curStage: 0},
	{stageIndex: 0},
	{DEBUG_STRING: 0},
	{DEBUG_NUMBER: 0},
	{TIMER_MULTIPLIER: 0},
	{monUID: 0},
	{valStart: 0},
	{scale: 0},
	{adAreaUID: 0},
	{radUID: 0},
	{CURRENT_TIME: 0},
	{CURRENT_SCORE: 0},
	{CURRENT_COINS: 0},
	{STARTING_EGGS_COUNT: 0},
	{MON_PICK_UP_TIME: 0},
	{MON_DROP_TIME: 0},
	{INPUT_CANCEL: 0},
	{deadZoneDist: 0},
	{inputAngle: 0},
	{joyAngle: 0},
	{playerWobbleAngle: 0},
	{playerFlipTolerance: 0},
	{playerSkipStep: 0},
	{playerStepTime: 0},
	{areaInnerMargin: 0},
	{areaUID: 0},
	{distMax: 0},
	{distMin: 0},
	{distThreshold: 0},
	{dist: 0},
	{ang: 0},
	{returnAvailability: 0},
	{foodUID: 0},
	{stackAssetCount: 0},
	{stackArrayLength: 0},
	{fruitSpawnRate: 0},
	{fruitRotTime: 0},
	{fruitRotTimeVar: 0},
	{fruitUID: 0},
	{hue_i: 0},
	{hue_f: 0},
	{LEVELS_INFANT_STAGE: 0},
	{LEVELS_TEEN_STAGE: 0},
	{LEVELS_ADULT_STAGE: 0},
	{MON_STAGE_LEVELS: 0},
	{MON_STAGE_PROGRESSION: 0},
	{followDistance: 0},
	{wanderTimeMin: 0},
	{wanderTimeMax: 0},
	{wanderDistMin: 0},
	{wanderDistMax: 0},
	{wanderDistThreshold: 0},
	{wanderSpeed: 0},
	{foodDetectDist: 0},
	{animSinePeriod: 0},
	{animSineBaseMagnitude: 0},
	{mon_HueShiftMax: 0},
	{canBePicked: 0},
	{lerpStep: 0},
	{flashingMonUID: 0},
	{flashingHueShift: 0},
	{spriteType: 0},
	{showUnavailable: 0},
	{monNeedBalloonWidth: 0},
	{monNeedBalloonHeight: 0},
	{eggHatchSpeed: 0},
	{eggHatchSpeedVar: 0},
	{shakeMagMax: 0},
	{shakeMagMin: 0},
	{shakePeriodMin: 0},
	{shakePeriodMax: 0},
	{timerRatio: 0},
	{moveMonUID: 0},
	{moveDist: 0},
	{moveX: 0},
	{moveY: 0},
	{foodPosOffset: 0},
	{returnSawFood: 0},
	{activeUID: 0},
	{currentStage: 0},
	{currentStageIndex: 0},
	{nextStage: 0},
	{evoWait: 0},
	{needEvoHighlight: 0},
	{stageSprite: 0},
	{audio_clip: 0},
	{sparkle: 0},
	{animSineJumpMultiplier: 0},
	{flipDistance: 0},
	{wanderDeformRatio: 0},
	{wanderJumpRatio: 0},
	{eatDeformRatio: 0},
	{eatTimer: 0},
	{monPlayerReactionDistance: 0},
	{popOffset: 0},
	{GUIDE_LEVEL: 0},
	{GUIDE_STEP: 0},
	{maxDist: 0},
	{maxAlpha: 0},
	{SHINY_BASE_CHANCE: 0},
	{SHINY_PARENT_CHANCE: 0},
	{minBreedTimer: 0},
	{maxBreedTimer: 0},
	{canBreed: 0},
	{parentTypes: 0},
	{randomType: 0},
	{shinyChance: 0},
	{coinSpreadMin: 0},
	{coinSpreadMax: 0},
	{count: 0},
	{coinUID: 0},
	{dropRateBase: 0},
	{dropRateMin: 0},
	{coinSpawnVariance: 0},
	{zUID: 0},
	{areaWidthExtra: 0},
	{areaHeightExtra: 0},
	{areaMarginLeft: 0},
	{areaMarginLeftShort: 0},
	{areaMarginTop: 0},
	{areaAnimGaps: 0},
	{animTime: 0},
	{animWidthDeformRatio: 0},
	{animLogBaseScale: 0},
	{yOffset: 0},
	{propUID: 0},
	{waitTime: 0},
	{width0: 0},
	{angle0: 0},
	{mirror: 0},
	{height0: 0},
	{dirtUID: 0},
	{ZOOM_FIRST: 0},
	{ZOOM_OUT_VALUE: 0},
	{panTime: 0},
	{zoomSpeed: 0},
	{zoomTol: 0},
	{maxViewport: 0},
	{maxRatio: 0},
	{multiplier: 0},
	{timer: 0},
	{cash: 0},
	{AD_WAIT_TIME_BASE: 0},
	{AD_WAIT_TIME_VAR: 0},
	{AD_TYPES: 0},
	{canTrigger: 0},
	{AD_TIMER: 0},
	{AD_DISPLAY_TIME: 0},
	{width: 0},
	{height: 0},
	{cashPrize: 0},
	{nextPriceRatio: 0},
	{penPrize: 0},
	{treePrize: 0},
	{HEXDIGTS: 0},
	{hex: 0},
	{DEX_COMPLETE: 0},
	{DEX_COMPLETE_SHINY: 0},
	{dexRed: 0},
	{dexGreen: 0},
	{dexBlue: 0},
	{per_line: 0},
	{monSize: 0},
	{monPercentDiff: 0},
	{monType: 0},
	{curKey: 0},
	{curType: 0},
	{curStatus: 0},
	{hintOffsetY: 0},
	{hintOffsetX: 0},
	{hasSpecie: 0},
	{isNewMon: 0},
	{keyIndex: 0},
	{isNewShiny: 0},
	{jsonKeyIndex: 0},
	{tol: 0},
	{isComplete: 0},
	{sparkSpawnFreq: 0},
	{maxSparkDist: 0},
	{minSparkDist: 0},
	{sparkMaxTime: 0},
	{sparkMinTime: 0}
];

self.InstanceType = {
	PokiSDK: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	jsonDataMons: class extends self.IJSONInstance {},
	jsonSaveField: class extends self.IJSONInstance {},
	jsonDataDex: class extends self.IJSONInstance {},
	playerFoodStack: class extends self.IArrayInstance {},
	playerMonTrail: class extends self.IArrayInstance {},
	player: class extends self.ISpriteInstance {},
	bgGrass: class extends self.ITiledBackgroundInstance {},
	areaActive: class extends self.ITiledBackgroundInstance {},
	txtDisplay: class extends self.ITextInstance {},
	txtData: class extends self.ITextInstance {},
	txtTimer: class extends self.ITextInstance {},
	sprFruit: class extends self.ISpriteInstance {},
	txtLevel: class extends self.ITextInstance {},
	prtStar: class extends self.IParticlesInstance {},
	tileArrows: class extends self.ITiledBackgroundInstance {},
	barProgress: class extends self.ISpriteInstance {},
	txtTime: class extends self.ITextInstance {},
	txtScore: class extends self.ITextInstance {},
	areaBuy: class extends self.ITiledBackgroundInstance {},
	sprChar: class extends self.ISpriteInstance {},
	uiKeyboardInput: class extends self.ISpriteInstance {},
	sprFruit2: class extends self.ISpriteInstance {},
	uiMobInputCenter: class extends self.ISpriteInstance {},
	uiMobInputAxis: class extends self.ISpriteInstance {},
	sprCoin: class extends self.ISpriteInstance {},
	uiCoins: class extends self.ISpriteInstance {},
	txtCash: class extends self.ITextInstance {},
	uiCoinFlying: class extends self.ISpriteInstance {},
	sprBeacon: class extends self.ISpriteInstance {},
	areaBuildZone: class extends self.ITiledBackgroundInstance {},
	uiCoinBuy: class extends self.ISpriteInstance {},
	radHalfLast: class extends self.ISpriteInstance {},
	radBase: class extends self.ISpriteInstance {},
	radMask: class extends self.ISpriteInstance {},
	radHalfFirst: class extends self.ISpriteInstance {},
	radQuadrant: class extends self.ISpriteInstance {},
	monBasic: class extends self.ISpriteInstance {},
	sprMonInfant: class extends self.ISpriteInstance {},
	sprMonTeen: class extends self.ISpriteInstance {},
	sprMonAdult: class extends self.ISpriteInstance {},
	sprMonEgg: class extends self.ISpriteInstance {},
	sprShadow: class extends self.ISpriteInstance {},
	sprHintLine: class extends self.ISpriteInstance {},
	_9pDirt: class extends self.IWorldInstance {},
	sprLog: class extends self.ISpriteInstance {},
	sprRope: class extends self.ISpriteInstance {},
	sprSign: class extends self.ISpriteInstance {},
	_9pBubble: class extends self.IWorldInstance {},
	sprPoint: class extends self.ISpriteInstance {},
	sprNeeds: class extends self.ISpriteInstance {},
	auxCam: class extends self.ISpriteInstance {},
	sprTree: class extends self.ISpriteInstance {},
	sprExitPoint: class extends self.ISpriteInstance {},
	_9pPenFloor: class extends self.IWorldInstance {},
	sprKnot: class extends self.ISpriteInstance {},
	prtShine: class extends self.IParticlesInstance {},
	sprFruitSpoiled: class extends self.ISpriteInstance {},
	prtDust: class extends self.IParticlesInstance {},
	areaTreeBuy: class extends self.ITiledBackgroundInstance {},
	_9pBuySpot: class extends self.IWorldInstance {},
	txtDropShadow: class extends self.ITextInstance {},
	sprProps: class extends self.ISpriteInstance {},
	sprGrass: class extends self.ISpriteInstance {},
	sprDust: class extends self.ISpriteInstance {},
	radTimer: class extends self.ISpriteInstance {},
	prtFlies: class extends self.IParticlesInstance {},
	uiTutorialMobile: class extends self.ISpriteInstance {},
	partBasic: class extends self.IParticlesInstance {},
	patMenuBg: class extends self.IWorldInstance {},
	colBasic: class extends self.ITiledBackgroundInstance {},
	areaRewardedAd: class extends self.ITiledBackgroundInstance {},
	uiIconAd: class extends self.ISpriteInstance {},
	sprBoost: class extends self.ISpriteInstance {},
	uiBoostIcon: class extends self.ISpriteInstance {},
	sprAdSpot: class extends self.ISpriteInstance {},
	sprZoom: class extends self.ISpriteInstance {},
	sprFarmForeground: class extends self.ISpriteInstance {},
	sprButterfly: class extends self.ISpriteInstance {},
	prtEvoShine: class extends self.IParticlesInstance {},
	sprSigns: class extends self.ISpriteInstance {},
	patMenuFw: class extends self.IWorldInstance {},
	sprButton: class extends self.ISpriteInstance {},
	uiDex: class extends self.ISpriteInstance {},
	prtShineCoin: class extends self.IParticlesInstance {},
	uiNotification: class extends self.ISpriteInstance {},
	uiWarning: class extends self.ISpriteInstance {},
	uiNo: class extends self.ISpriteInstance {},
	_9pPenDesert: class extends self.IWorldInstance {},
	_9pPenWater: class extends self.IWorldInstance {},
	_9pPenJungle: class extends self.IWorldInstance {},
	_9pPenBreeding: class extends self.IWorldInstance {},
	_9pPenEgg: class extends self.IWorldInstance {},
	sprCharArm: class extends self.ISpriteInstance {},
	_9pUiInfo: class extends self.IWorldInstance {},
	uiSettings: class extends self.ISpriteInstance {},
	uiHintColor: class extends self.ISpriteInstance {},
	uiSFX: class extends self.ISpriteInstance {},
	uiMusic: class extends self.ISpriteInstance {},
	patSettingsBg: class extends self.IWorldInstance {},
	txtTitle: class extends self.ITextInstance {},
	btnExit: class extends self.ISpriteInstance {},
	sprDexNotif: class extends self.ISpriteInstance {},
	sprSparkle: class extends self.ISpriteInstance {},
	_9pPenAdult: class extends self.IWorldInstance {},
	uiPickUp: class extends self.ISpriteInstance {},
	sprBreedNest: class extends self.ISpriteInstance {},
	sprFarmLayout3: class extends self.ISpriteInstance {},
	prtShinySparke: class extends self.IParticlesInstance {},
	uiShinyDex: class extends self.ISpriteInstance {},
	famFood: class extends self.ISpriteInstance {},
	famMons: class extends self.ISpriteInstance {},
	famSpritesMon: class extends self.ISpriteInstance {},
	famZorder: class extends self.ISpriteInstance {},
	famScanAreas: class extends self.ITiledBackgroundInstance {},
	famScanObjects: class extends self.ISpriteInstance {},
	famAnimDirt: class extends self.IWorldInstance {},
	famAnimProp: class extends self.ISpriteInstance {},
	famDropShadowed: class extends self.ITextInstance {},
	famAreaBuy: class extends self.ITiledBackgroundInstance {},
	famTimeScaledSpr: class extends self.ISpriteInstance {},
	famDexContent: class extends self.ISpriteInstance {},
	famZorderParent: class extends self.ISpriteInstance {},
	famSpritesMonAux: class extends self.ISpriteInstance {},
	famTimeScaledBg: class extends self.ITiledBackgroundInstance {},
	famTimeScaled9p: class extends self.IWorldInstance {}
}